ouaf/ouaf/urls.py
from django.contrib import admin
from django.urls import path, include, re_path, reverse_lazy
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views


urlpatterns = [
    #path("admin/", admin.site.urls), no need to use that because we include it in the urlspatterns
    path("", include('ouaf_app.urls')),
    path("index/", RedirectView.as_view(url="/", permanent=True)),
    path("i18n/", include("django.conf.urls.i18n")),
    # TO use i18n within JS scripts #
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path(
        "account/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html",
            success_url=reverse_lazy("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path("", include("ouaf_app.urls")),
    path("backoffice/", include('ouaf_backoffice_app.urls')),
    prefix_default_language=True,
)

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    # Dev
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + debug_toolbar_urls()
else:
    # Prod sans Nginx/Apache
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ouaf/ouaf_backoffice_app/urls.py
from django.urls import path, include
from . import views

app_name = "backoffice"

urlpatterns = [
    path("", views.BackofficeHome.as_view(), name="home"),

    path("users/", views.UserListView.as_view(), name="user_list"),
    path("users/<int:pk>/edit/", views.UserUpdateView.as_view(), name="user_edit"),

    path("activities/", views.ActivityListView.as_view(), name="activity_list"),
    path("activities/new/", views.ActivityCreateView.as_view(), name="activity_create"),
    path("activities/<int:pk>/", views.ActivityDetailView.as_view(), name="activity_detail"),
    path("activities/<int:pk>/update/", views.ActivityUpdateView.as_view(), name="activity_update"),
    path("activities/<int:pk>/delete/", views.ActivityDeleteView.as_view(), name="activity_delete"),
    path("activities/categories/new/modal/", views.ActivityCategoryCreateModalView.as_view(),
         name="activity_category_modal", ),

    path("events/", views.EventListView.as_view(), name="event_list"),
    path("events/new/", views.EventCreateView.as_view(), name="event_create"),
    path("events/<int:pk>/edit/", views.EventUpdateView.as_view(), name="event_edit"),
    path("events/<int:pk>/delete/", views.EventDeleteView.as_view(), name="event_delete"),

    path("animals/", views.AnimalListView.as_view(), name="animal_list"),
    path("animals/new", views.AnimalCreateView.as_view(), name="animal_create"),
    path("animals/<int:pk>/edit/", views.AnimalEditView.as_view(), name="animal_edit"),
    path("animals/<int:pk>/delete/", views.AnimalDeleteView.as_view(), name="animal_delete"),

    path("team/", views.TeamMemberListView.as_view(), name="team_list"),
    path("team/new", views.TeamMemberCreateView.as_view(), name="team_create"),
    path("team/<int:pk>/edit/", views.TeamMemberUpdateView.as_view(), name="team_update"),
    path("team/<int:pk>/delete/", views.TeamMemberDeleteView.as_view(), name="team_delete")
]

ouaf/ouaf_backoffice_app/models.py
from django.db import models

# Create your models here.

ouaf/ouaf_backoffice_app/forms.py
from django import forms
from ouaf_app.models import Person, Animal
from ouaf_app.groups import *
from django.utils.translation import gettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField as PhoneFormField


class PersonEditForm(forms.ModelForm):
    username = forms.CharField(required=True, label=_("Nom d’utilisateur"))
    first_name = forms.CharField(required=True, label=_("Prénom"))
    last_name = forms.CharField(required=True, label=_("Nom"))
    email = forms.EmailField(required=True, label=_("Adresse e-mail"))
    is_volunteer = forms.BooleanField(required=False, label=_("Bénévole"))
    is_member = forms.BooleanField(required=False, label=_("Adhérent"))
    phone_number = PhoneFormField(region="FR", required=True)


    class Meta:
        model = Person
        fields = [
            "first_name",
            "last_name",
            "email",
            "username",
            "address",
            "city",
            "country",
            "phone_number",
            "newsletter_subscription",
        ]
        labels = {
            "address": _("Adresse"),
            "city": _("Ville"),
            "country": _("Pays"),
            "newsletter_subscription": _("Abonnement à la newsletter"),
        }

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance', None)
        if instance:
            kwargs['initial'] = {
                'is_volunteer': instance.belongs_to_group(GROUP_VOLUNTEER),
                'is_member': instance.belongs_to_group(GROUP_MEMBER),
            }
        super().__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.set_group(GROUP_VOLUNTEER, self.cleaned_data['is_volunteer'])

        self.instance.set_group(GROUP_MEMBER, self.cleaned_data['is_member'])
        return super().save(*args, **kwargs)


class MediaForm(forms.ModelForm):
    template_name = "backoffice/forms/media.html"

ouaf/ouaf_backoffice_app/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin
from django import forms
from django.contrib import messages
from django.forms import inlineformset_factory, BaseFormSet, modelformset_factory
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DeleteView, UpdateView, CreateView, DetailView
from .mixins import BackofficeAccessRequiredMixin
from ouaf_app.models import Event, Animal, Activity, OrganisationChartEntry, ActivityMedia, ActivityCategory, \
    AnimalMedia
from .forms import PersonEditForm, MediaForm
from ouaf_app.signals import *
from django.db import transaction
from django.utils.translation import gettext as _

User = get_user_model()


#On top of the page for better compatibility
def _is_ajax(request):
    return request.headers.get("x-requested-with") == "XMLHttpRequest"


class BackofficeHome(BackofficeAccessRequiredMixin, TemplateView):
    template_name = "backoffice/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sections"] = [
            {"label": "Utilisateurs", "url": reverse_lazy("backoffice:user_list")},
            {"label": "Événements", "url": reverse_lazy("backoffice:event_list")},
            {"label": "Animaux", "url": reverse_lazy("backoffice:animal_list")},
            {"label": "Activites", "url": reverse_lazy("backoffice:activity_list")},
            {"label": "Team Members", "url": reverse_lazy("backoffice:team_list")}
            ##
        ]
        return context


class UserListView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    template_name = "backoffice/users/list.html"
    permission_required = person_view.perm_name()
    raise_exception = True


class UserUpdateView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    form_class = PersonEditForm
    template_name = 'backoffice/users/form.html'
    permission_required = person_change.perm_name()
    success_url = reverse_lazy("backoffice:user_list")
    raise_exception = True


class EventListView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, ListView):
    model = Event
    template_name = "backoffice/events/list.html"
    permission_required = event_view.perm_name()
    raise_exception = True


class EventCreateView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Event
    fields = ["summary", "description", "start", "until", "duration",
              "organizer", "attendees", "address", "latitude", "longitude", "is_published"]
    template_name = "backoffice/events/form.html"
    permission_required = event_add.perm_name()
    success_url = reverse_lazy("backoffice:event_list")
    raise_exception = True


class EventUpdateView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Event
    fields = ["summary", "description", "start", "until", "duration",
              "organizer", "attendees", "address", "latitude", "longitude", "is_published"]
    template_name = "backoffice/events/form.html"
    permission_required = event_change.perm_name()
    success_url = reverse_lazy("backoffice:event_list")
    raise_exception = True


class EventDeleteView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Event
    template_name = "backoffice/events/confirm_delete.html"
    permission_required = event_delete.perm_name()
    success_url = reverse_lazy('backoffice:event_list')
    raise_exception = True


class AnimalListView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, ListView):
    model = Animal
    template_name = "backoffice/animals/list.html"
    permission_required = animal_view.perm_name()
    raise_exception = True


class AnimalCreateView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Animal
    fields = ["name", "description", "birth", "death", "pet_amount"]
    template_name = "backoffice/animals/form.html"
    permission_required = animal_add.perm_name()
    success_url = reverse_lazy('backoffice:animal_list')
    raise_exception = True

    def _create_formset_class(self):
        return inlineformset_factory(
            Animal,
            AnimalMedia,
            form=MediaForm,
            fields=["file", "url", "caption", "position"],
            extra=1,
            can_delete=True,
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        FormSet = self._create_formset_class()
        if self.request.method == "POST":
            ctx["media_formset"] = FormSet(self.request.POST, self.request.FILES)
        else:
            ctx["media_formset"] = FormSet()
        return ctx

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        FormSet = self._create_formset_class()
        media_formset = FormSet(request.POST, request.FILES)

        print("post")
        print(form.is_valid())
        print(media_formset.is_valid())
        if form.is_valid() and media_formset.is_valid():
            print("valid")
            with transaction.atomic():
                self.object = form.save()
                media_formset.instance = self.object
                media_formset.save()

            messages.success(request, "Animal créé.")
            return redirect(self.get_success_url())
        else:
            print(media_formset.error_messages)
            print("invalid")

        context = self.get_context_data(form=form)
        return self.render_to_response(context)


class AnimalEditView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Animal
    fields = ["name", "description", "birth", "death", "pet_amount"]
    template_name = "backoffice/animals/update.html"
    permission_required = animal_change.perm_name()
    success_url = reverse_lazy('backoffice:animal_list')
    raise_exception = True

    def _update_formset_class(self):
        return inlineformset_factory(
            Animal,
            AnimalMedia,
            form=MediaForm,
            fields=["file", "url", "caption", "position"],
            extra=0,
            can_delete=True
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        UpdateFormSet = self._update_formset_class()
        if self.request.method == "POST":
            ctx["media_formset"] = UpdateFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            ctx["media_formset"] = UpdateFormSet(instance=self.object)
        return ctx

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        UpdateFormSet = self._update_formset_class()
        media_formset = UpdateFormSet(request.POST, request.FILES, instance=self.object)

        print("update")
        print(form.is_valid())
        print(media_formset.is_valid())
        if form.is_valid() and media_formset.is_valid():
            with transaction.atomic():
                self.object = form.save()
                media_formset.save()
            messages.success(request, "Animal mis à jour.")
            return redirect(self.get_success_url())
        else:
            print(media_formset.error_messages)
            print("invalid")

        return self.render_to_response({
            "form": form,
            "animal": self.object,
            "media_formset": media_formset,
        })


class AnimalDeleteView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Animal
    template_name = "backoffice/animals/confirm_delete.html"
    permission_required = animal_delete.perm_name()
    success_url = reverse_lazy('backoffice:animal_list')
    raise_exception = True


class ActivityListView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, ListView):
    model = Activity
    template_name = "backoffice/activities/list.html"
    permission_required = activity_view.perm_name()
    raise_exception = True

    def get_queryset(self):
        return (
            Activity.objects
            .all()
            .prefetch_related("media")
        )


class ActivityCreateView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Activity
    fields = ["title", "category", "description"]
    template_name = "backoffice/activities/form.html"
    permission_required = activity_add.perm_name()
    success_url = reverse_lazy("backoffice:activity_list")
    raise_exception = True

    def _create_formset_class(self):
        return inlineformset_factory(
            Activity,
            ActivityMedia,
            form=MediaForm,
            fields=["file", "url", "caption", "position"],
            extra=2,
            can_delete=True,
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        FormSet = self._create_formset_class()
        if self.request.method == "POST":
            ctx["media_formset"] = FormSet(self.request.POST, self.request.FILES)
        else:
            ctx["media_formset"] = FormSet()
        return ctx

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        FormSet = self._create_formset_class()
        media_formset = FormSet(request.POST, request.FILES)

        if form.is_valid() and media_formset.is_valid():
            with transaction.atomic():
                self.object = form.save()
                media_formset.instance = self.object
                media_formset.save()

            messages.success(request, "Activité créée.")
            return redirect(self.get_success_url())

        context = self.get_context_data(form=form)

ouaf/ouaf_backoffice_app/templates/backoffice/activities/detail.html
{% extends "base.html" %}

{% block title %}Détail activité – Backoffice{% endblock %}

{% block content %}
<section class="boActivityDetail" aria-labelledby="activity-detail-title">
  <header class="boActivityDetail__header">
    <h1 id="activity-detail-title">{{ object.title }}</h1>
    <div class="boActivityDetail__actions">
      <a class="btn btn--primary" href="{% url 'backoffice:activity_update' object.pk %}">Modifier</a>
      <a class="btn btn--danger" href="{% url 'backoffice:activity_delete' object.pk %}">Supprimer</a>
      <a class="btn btn--ghost" href="{% url 'backoffice:activity_list' %}">Retour</a>
    </div>
  </header>

  <article class="boActivityDetail__content">
    {% if object.category %}
      <p><strong>Catégorie :</strong> {{ object.category.title }}</p>
    {% endif %}

    {% if object.image %}
      <p>
        <img src="{{ object.image.url }}" alt="Visuel {{ object.title }}" style="max-width:340px;height:auto;border-radius:8px;border:1px solid var(--clr-primary-dark);">
      </p>
    {% endif %}

    {% if object.description %}
      <h2>Description</h2>
      <p>{{ object.description }}</p>
    {% endif %}

    <h2>Médias</h2>
    {% if media_list %}
      <ul class="boActivityDetail__media" role="list" style="display:flex;flex-wrap:wrap;gap:1rem;padding:0;margin:0;">
        {% for m in media_list %}
          <li style="list-style:none;max-width:280px;">
            {% if m.is_image %}
              <img src="{{ m.file.url|default:m.url }}" alt="{{ m.caption }}" style="width:100%;height:auto;border-radius:6px;border:1px solid #eee;">
            {% elif m.is_video %}
              {% if 'youtu' in m.url %}
                <a class="btn btn--ghost" href="{{ m.url }}" target="_blank" rel="noopener">Ouvrir la vidéo</a>
              {% else %}
                <video src="{{ m.file.url|default:m.url }}" controls style="width:100%;border-radius:6px;"></video>
              {% endif %}
            {% else %}
              <a href="{{ m.file.url|default:m.url }}" target="_blank" rel="noopener">Voir le média</a>
            {% endif %}
            {% if m.caption %}
              <p class="form__help" style="margin:.25rem 0 0;">{{ m.caption }}</p>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="form__help">Aucun média associé.</p>
    {% endif %}
  </article>
</section>
{% endblock %}

ouaf/ouaf_backoffice_app/templates/backoffice/activities/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Activités – Backoffice{% endblock %}

{% block content %}
<section class="boActivities" aria-labelledby="boActivities-title">
  <header class="boActivities__header">
    <h1 id="boActivities-title">Activités</h1>
    <div class="boActivities__actions">
      <a class="btn btn--primary" href="{% url 'backoffice:activity_create' %}">+ Nouvelle activité</a>
    </div>
  </header>

  {% if object_list %}
    <ul class="boActivities__list" role="list">
      {% for a in object_list %}
        <li class="boActivities__item">
          <article class="boActivities__card">
            <a class="boActivities__thumbLink" href="{% url 'backoffice:activity_update' a.pk %}">
              {% if a.image %}
                <img class="boActivities__thumb" src="{{ a.image.url }}" alt="Visuel de {{ a.title }}" loading="lazy" decoding="async">
              {% else %}
                <img class="boActivities__thumb" src="{% static 'images/avatar_placeholder.svg' %}" alt="Aperçu indisponible" loading="lazy" decoding="async">
              {% endif %}
            </a>

            <div class="boActivities__meta">
              <h3 class="boActivities__title">
                <a class="boActivities__titleLink" href="{% url 'backoffice:activity_update' a.pk %}">{{ a.title }}</a>
              </h3>
              {% if a.category %}
                <p class="boActivities__category">{{ a.category.title }}</p>
              {% endif %}
              {% if a.description %}
                <p class="boActivities__desc">{{ a.description|truncatechars:140 }}</p>
              {% endif %}
              <p class="boActivities__medias">
                Médias liés : {{ a.media.count }}
              </p>
            </div>

            <div class="boActivities__actionsRow">
              <a class="btn btn--ghost" href="{% url 'backoffice:activity_detail' a.pk %}">Voir</a>
              <a class="btn btn--primary" href="{% url 'backoffice:activity_update' a.pk %}">Modifier</a>
              <a class="btn btn--danger" href="{% url 'backoffice:activity_delete' a.pk %}">Supprimer</a>
            </div>
          </article>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <div class="boActivities__empty">
      <p>Aucune activité pour le moment.</p>
      <p><a class="btn btn--primary" href="{% url 'backoffice:activity_create' %}">Créer la première activité</a></p>
    </div>
  {% endif %}
</section>
{% endblock %}

ouaf/ouaf_backoffice_app/templates/backoffice/activities/update.html
{% extends "base.html" %}

{% block title %}Modifier l’activité – Backoffice{% endblock %}

{% block content %}
    <section class="account" aria-labelledby="activity-update-title">
        <div class="account__card">
            <header class="account__head">
                <h1 id="activity-update-title" class="account__title">Modifier : {{ object.title }}</h1>
                <p class="account__meta">ID #{{ object.pk }}</p>
            </header>

            <form class="account__body" method="post" enctype="multipart/form-data"
                  action="{% url 'backoffice:activity_update' object.pk %}">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    <div class="form__nonfield">{{ form.non_field_errors }}</div>
                {% endif %}

                <div class="formGrid">
                    <!-- Titre -->
                    <div class="form__row span-full">
                        <label class="form__label" for="{{ form.title.id_for_label }}">Titre <span
                                class="form__required">*</span></label>
                        {{ form.title }}
                        {% if form.title.errors %}
                            <div class="form__errors">{{ form.title.errors }}</div>{% endif %}
                    </div>

                    <!-- Catégorie + modal -->
                    <div class="form__row">
                        <label class="form__label" for="{{ form.category.id_for_label }}">Catégorie</label>
                        <div style="display:flex; gap:.5rem; align-items:center; flex-wrap:wrap;">
                            {{ form.category }}
                            <a href="{% url 'backoffice:activity_category_modal' %}"
                               class="btn btn--ghost js-open-cat"
                               data-modal-url="{% url 'backoffice:activity_category_modal' %}">
                                + Nouvelle catégorie
                            </a>
                        </div>
                        {% if form.category.errors %}
                            <div class="form__errors">{{ form.category.errors }}</div>{% endif %}
                    </div>

                    <!-- Description -->
                    <div class="form__row span-full">
                        <label class="form__label" for="{{ form.description.id_for_label }}">Description <span
                                class="form__required">*</span></label>
                        {{ form.description }}
                        {% if form.description.errors %}
                            <div class="form__errors">{{ form.description.errors }}</div>{% endif %}
                    </div>
                </div>

                <!-- Modal catégorie (chargée en AJAX) -->
                <dialog id="catModal"
                        style="max-width:600px; width:clamp(320px, 90vw, 600px); border:1px solid var(--clr-primary-dark); border-radius: var(--radius); padding:0;">
                    <div class="account__card" style="margin:0; border:none; box-shadow:none;">
                        <header class="account__head">
                            <h2 class="account__title" style="margin:0;">Créer une catégorie</h2>
                            <p class="account__meta">Ajoutez une nouvelle catégorie sans quitter la page.</p>
                        </header>
                        <div id="catModalContent" class="account__body"><!-- contenu chargé en AJAX --></div>
                    </div>
                </dialog>

                <hr class="sep"/>

                <!-- MEDIAS (inline formset éditable) -->
                <h2 class="account__title" style="margin-top:1rem;">Médias</h2>

                {% if media_formset.non_form_errors %}
                    <div class="form__nonfield">{{ media_formset.non_form_errors }}</div>
                {% endif %}

                {{ media_formset.management_form }}

                <div id="media-forms" class="formGrid">
                    {% for mf in media_formset %}
                        {{ mf }}
                    {% endfor %}
                </div>

                <div id="empty-form" style="display:none;">
                    {{ media_formset.empty_form }}
                </div>

                <div style="margin-top:.75rem;">
                    <button type="button" class="btn btn--ghost" id="add-media">+ Ajouter un média</button>
                </div>

                <script>
                    (function () {
                        const prefix = "{{ media_formset.management_form.prefix }}";
                        const total = document.getElementById(`id_${prefix}-TOTAL_FORMS`);
                        const list = document.getElementById('media-forms');
                        const tpl = document.getElementById('empty-form').innerHTML;

                        document.getElementById('add-media')?.addEventListener('click', () => {
                            const idx = parseInt(total.value, 10);
                            const html = tpl.replaceAll('__prefix__', idx);
                            const wrap = document.createElement('div');
                            wrap.innerHTML = html;
                            list.appendChild(wrap.firstElementChild);
                            total.value = idx + 1;
                        });
                    })();
                </script>


                <footer class="account__foot">
                    <a class="btn btn--danger" href="{% url 'backoffice:activity_delete' object.pk %}">Supprimer</a>
                    <a class="btn btn--ghost" href="{% url 'backoffice:activity_list' %}">Annuler</a>
                    <button class="btn btn--primary" type="submit">Enregistrer</button>
                </footer>
            </form>

        </div>
    </section>

    <script>
        /* --- Modal catégorie (AJAX, n’envoie pas le formulaire principal) --- */
        document.addEventListener('DOMContentLoaded', () => {
            const openBtn = document.querySelector('.js-open-cat');
            const modal = document.getElementById('catModal');
            const content = document.getElementById('catModalContent');
            const categorySelect = document.getElementById('id_category');

            if (!openBtn || !modal || !content || !categorySelect) return;

            function wireModalEvents(root) {
                root.querySelectorAll('[data-close-modal]').forEach(btn => {
                    btn.addEventListener('click', () => modal.close());
                });

                const form = root.querySelector('#catForm');
                if (form) {
                    form.addEventListener('submit', async (e) => {
                        e.preventDefault();
                        const fd = new FormData(form);
                        try {
                            const res = await fetch(form.action, {
                                method: 'POST',
                                body: fd,
                                headers: {'X-Requested-With': 'XMLHttpRequest'},
                            });

                            if (res.ok && res.headers.get('content-type')?.includes('application/json')) {
                                const data = await res.json();
                                const opt = new Option(data.title, data.id, true, true);
                                categorySelect.add(opt);
                                categorySelect.value = data.id;
                                modal.close();
                                return;
                            }

                            const html = await res.text();
                            content.innerHTML = html;
                            wireModalEvents(content);
                        } catch (err) {
                            console.error(err);
                        }
                    });
                }
            }

            openBtn.addEventListener('click', async (e) => {
                e.preventDefault();
                const url = openBtn.dataset.modalUrl || openBtn.href;
                try {
                    const res = await fetch(url, {headers: {'X-Requested-With': 'XMLHttpRequest'}});
                    const html = await res.text();
                    content.innerHTML = html;
                    wireModalEvents(content);
                    if (typeof modal.showModal === 'function') {
                        modal.showModal();
                    } else {
                        modal.setAttribute('open', 'open');
                    }
                } catch (err) {
                    console.error(err);
                }
            });
        });
    </script>

    <script>
        /* --- Ajout dynamique d’un média (inline formset) --- */
        (function () {
            const addBtn = document.getElementById('add-media');
            const container = document.getElementById('media-forms');
            const totalForms = document.querySelector('input[name$="-TOTAL_FORMS"]');

            function buildEmptyForm(nextIndex) {
                const sample = container.querySelector('.form__row.span-full');
                const clone = sample.cloneNode(true);

                // Reindex + reset champs
                clone.querySelectorAll('input, textarea, select, label').forEach(el => {
                    if (el.name) el.name = el.name.replace(/\-\d+\-/g, `-${nextIndex}-`);
                    if (el.id) el.id = el.id.replace(/\-\d+\-/g, `-${nextIndex}-`);
                    if (el.getAttribute && el.getAttribute('for')) {
                        el.setAttribute('for', el.getAttribute('for').replace(/\-\d+\-/g, `-${nextIndex}-`));
                    }
                    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                        if (el.type === 'checkbox' || el.type === 'radio') el.checked = false;
                        else el.value = '';
                    }
                });

                // Nouveau formulaire: enlever la case DELETE si présente
                const delWrap = clone.querySelector('[name$="-DELETE"]')?.closest('.form__row');
                if (delWrap) delWrap.remove();

                // Met à jour le titre "Média #n"
                const title = clone.querySelector('p.form__label strong');
                if (title) title.textContent = `Média #${nextIndex + 1}`;

                return clone;
            }

            addBtn?.addEventListener('click', () => {
                const nextIndex = parseInt(totalForms.value, 10);
                const newBlock = buildEmptyForm(nextIndex);
                container.appendChild(newBlock);
                totalForms.value = nextIndex + 1;
            });
        })();
    </script>
{% endblock %}