ouaf/ouaf/urls.py
from django.contrib import admin
from django.urls import path, include, re_path, reverse_lazy
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views


urlpatterns = [
    #path("admin/", admin.site.urls), no need to use that because we include it in the urlspatterns
    path("", include('ouaf_app.urls')),
    path("index/", RedirectView.as_view(url="/", permanent=True)),
    path("i18n/", include("django.conf.urls.i18n")),
    # TO use i18n within JS scripts #
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path(
        "account/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html",
            success_url=reverse_lazy("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path("", include("ouaf_app.urls")),
    path("backoffice/", include('ouaf_backoffice_app.urls')),
    prefix_default_language=True,
)

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    # Dev
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + debug_toolbar_urls()
else:
    # Prod sans Nginx/Apache
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ouaf/ouaf_backoffice_app/urls.py
from django.urls import path, include
from . import views

app_name = "backoffice"

urlpatterns = [
    path("", views.BackofficeHome.as_view(), name="home"),

    path("users/", views.UserListView.as_view(), name="user_list"),
    path("users/<int:pk>/edit/", views.UserUpdateView.as_view(), name="user_edit"),

    path("activities/", views.ActivityListView.as_view(), name="activity_list"),
    path("activities/new/", views.ActivityCreateView.as_view(), name="activity_create"),
    path("activities/<int:pk>/", views.ActivityDetailView.as_view(), name="activity_detail"),
    path("activities/<int:pk>/update/", views.ActivityUpdateView.as_view(), name="activity_update"),
    path("activities/<int:pk>/delete/", views.ActivityDeleteView.as_view(), name="activity_delete"),
    path("activities/categories/new/modal/", views.ActivityCategoryCreateModalView.as_view(),
         name="activity_category_modal", ),

    path("events/", views.EventListView.as_view(), name="event_list"),
    path("events/new/", views.EventCreateView.as_view(), name="event_create"),
    path("events/<int:pk>/edit/", views.EventUpdateView.as_view(), name="event_edit"),
    path("events/<int:pk>/delete/", views.EventDeleteView.as_view(), name="event_delete"),

    path("animals/", views.AnimalListView.as_view(), name="animal_list"),
    path("animals/new", views.AnimalCreateView.as_view(), name="animal_create"),
    path("animals/<int:pk>/edit/", views.AnimalEditView.as_view(), name="animal_edit"),
    path("animals/<int:pk>/delete/", views.AnimalDeleteView.as_view(), name="animal_delete"),

    path("team/", views.TeamMemberListView.as_view(), name="team_list"),
    path("team/new", views.TeamMemberCreateView.as_view(), name="team_create"),
    path("team/<int:pk>/edit/", views.TeamMemberUpdateView.as_view(), name="team_update"),
    path("team/<int:pk>/delete/", views.TeamMemberDeleteView.as_view(), name="team_delete")
]

ouaf/ouaf_backoffice_app/models.py
from django.db import models

# Create your models here.

ouaf/ouaf_backoffice_app/forms.py
from django import forms
from ouaf_app.models import Person, Animal
from ouaf_app.groups import *
from django.utils.translation import gettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField as PhoneFormField


class PersonEditForm(forms.ModelForm):
    username = forms.CharField(required=True, label=_("Nom d’utilisateur"))
    first_name = forms.CharField(required=True, label=_("Prénom"))
    last_name = forms.CharField(required=True, label=_("Nom"))
    email = forms.EmailField(required=True, label=_("Adresse e-mail"))
    is_volunteer = forms.BooleanField(required=False, label=_("Bénévole"))
    is_member = forms.BooleanField(required=False, label=_("Adhérent"))
    phone_number = PhoneFormField(region="FR", required=True)


    class Meta:
        model = Person
        fields = [
            "first_name",
            "last_name",
            "email",
            "username",
            "address",
            "city",
            "country",
            "phone_number",
            "newsletter_subscription",
        ]
        labels = {
            "address": _("Adresse"),
            "city": _("Ville"),
            "country": _("Pays"),
            "newsletter_subscription": _("Abonnement à la newsletter"),
        }

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance', None)
        if instance:
            kwargs['initial'] = {
                'is_volunteer': instance.belongs_to_group(GROUP_VOLUNTEER),
                'is_member': instance.belongs_to_group(GROUP_MEMBER),
            }
        super().__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.set_group(GROUP_VOLUNTEER, self.cleaned_data['is_volunteer'])

        self.instance.set_group(GROUP_MEMBER, self.cleaned_data['is_member'])
        return super().save(*args, **kwargs)


class MediaForm(forms.ModelForm):
    template_name = "backoffice/forms/media.html"

ouaf/ouaf_backoffice_app/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin
from django import forms
from django.contrib import messages
from django.forms import inlineformset_factory, BaseFormSet, modelformset_factory
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DeleteView, UpdateView, CreateView, DetailView
from .mixins import BackofficeAccessRequiredMixin
from ouaf_app.models import Event, Animal, Activity, OrganisationChartEntry, ActivityMedia, ActivityCategory, \
    AnimalMedia
from .forms import PersonEditForm, MediaForm
from ouaf_app.signals import *
from django.db import transaction
from django.utils.translation import gettext as _

User = get_user_model()


#On top of the page for better compatibility
def _is_ajax(request):
    return request.headers.get("x-requested-with") == "XMLHttpRequest"


class BackofficeHome(BackofficeAccessRequiredMixin, TemplateView):
    template_name = "backoffice/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sections"] = [
            {"label": "Utilisateurs", "url": reverse_lazy("backoffice:user_list")},
            {"label": "Événements", "url": reverse_lazy("backoffice:event_list")},
            {"label": "Animaux", "url": reverse_lazy("backoffice:animal_list")},
            {"label": "Activites", "url": reverse_lazy("backoffice:activity_list")},
            {"label": "Team Members", "url": reverse_lazy("backoffice:team_list")}
            ##
        ]
        return context


class UserListView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    template_name = "backoffice/users/list.html"
    permission_required = person_view.perm_name()
    raise_exception = True


class UserUpdateView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    form_class = PersonEditForm
    template_name = 'backoffice/users/form.html'
    permission_required = person_change.perm_name()
    success_url = reverse_lazy("backoffice:user_list")
    raise_exception = True


class EventListView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, ListView):
    model = Event
    template_name = "backoffice/events/list.html"
    permission_required = event_view.perm_name()
    raise_exception = True


class EventCreateView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Event
    fields = ["summary", "description", "start", "until", "duration",
              "organizer", "attendees", "address", "latitude", "longitude", "is_published"]
    template_name = "backoffice/events/form.html"
    permission_required = event_add.perm_name()
    success_url = reverse_lazy("backoffice:event_list")
    raise_exception = True


class EventUpdateView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Event
    fields = ["summary", "description", "start", "until", "duration",
              "organizer", "attendees", "address", "latitude", "longitude", "is_published"]
    template_name = "backoffice/events/form.html"
    permission_required = event_change.perm_name()
    success_url = reverse_lazy("backoffice:event_list")
    raise_exception = True


class EventDeleteView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Event
    template_name = "backoffice/events/confirm_delete.html"
    permission_required = event_delete.perm_name()
    success_url = reverse_lazy('backoffice:event_list')
    raise_exception = True


class AnimalListView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, ListView):
    model = Animal
    template_name = "backoffice/animals/list.html"
    permission_required = animal_view.perm_name()
    raise_exception = True


class AnimalCreateView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Animal
    fields = ["name", "description", "birth", "death", "pet_amount"]
    template_name = "backoffice/animals/form.html"
    permission_required = animal_add.perm_name()
    success_url = reverse_lazy('backoffice:animal_list')
    raise_exception = True

    def _create_formset_class(self):
        return inlineformset_factory(
            Animal,
            AnimalMedia,
            form=MediaForm,
            fields=["file", "url", "caption", "position"],
            extra=1,
            can_delete=True,
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        FormSet = self._create_formset_class()
        if self.request.method == "POST":
            ctx["media_formset"] = FormSet(self.request.POST, self.request.FILES)
        else:
            ctx["media_formset"] = FormSet()
        return ctx

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        FormSet = self._create_formset_class()
        media_formset = FormSet(request.POST, request.FILES)

        print("post")
        print(form.is_valid())
        print(media_formset.is_valid())
        if form.is_valid() and media_formset.is_valid():
            print("valid")
            with transaction.atomic():
                self.object = form.save()
                media_formset.instance = self.object
                media_formset.save()

            messages.success(request, "Animal créé.")
            return redirect(self.get_success_url())
        else:
            print(media_formset.error_messages)
            print("invalid")

        context = self.get_context_data(form=form)
        return self.render_to_response(context)


class AnimalEditView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Animal
    fields = ["name", "description", "birth", "death", "pet_amount"]
    template_name = "backoffice/animals/update.html"
    permission_required = animal_change.perm_name()
    success_url = reverse_lazy('backoffice:animal_list')
    raise_exception = True

    def _update_formset_class(self):
        return inlineformset_factory(
            Animal,
            AnimalMedia,
            form=MediaForm,
            fields=["file", "url", "caption", "position"],
            extra=0,
            can_delete=True
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        UpdateFormSet = self._update_formset_class()
        if self.request.method == "POST":
            ctx["media_formset"] = UpdateFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            ctx["media_formset"] = UpdateFormSet(instance=self.object)
        return ctx

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        UpdateFormSet = self._update_formset_class()
        media_formset = UpdateFormSet(request.POST, request.FILES, instance=self.object)

        print("update")
        print(form.is_valid())
        print(media_formset.is_valid())
        if form.is_valid() and media_formset.is_valid():
            with transaction.atomic():
                self.object = form.save()
                media_formset.save()
            messages.success(request, "Animal mis à jour.")
            return redirect(self.get_success_url())
        else:
            print(media_formset.error_messages)
            print("invalid")

        return self.render_to_response({
            "form": form,
            "animal": self.object,
            "media_formset": media_formset,
        })


class AnimalDeleteView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Animal
    template_name = "backoffice/animals/confirm_delete.html"
    permission_required = animal_delete.perm_name()
    success_url = reverse_lazy('backoffice:animal_list')
    raise_exception = True


class ActivityListView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, ListView):
    model = Activity
    template_name = "backoffice/activities/list.html"
    permission_required = activity_view.perm_name()
    raise_exception = True

    def get_queryset(self):
        return (
            Activity.objects
            .all()
            .prefetch_related("media")
        )


class ActivityCreateView(BackofficeAccessRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Activity
    fields = ["title", "category", "description"]
    template_name = "backoffice/activities/form.html"
    permission_required = activity_add.perm_name()
    success_url = reverse_lazy("backoffice:activity_list")
    raise_exception = True

    def _create_formset_class(self):
        return inlineformset_factory(
            Activity,
            ActivityMedia,
            form=MediaForm,
            fields=["file", "url", "caption", "position"],
            extra=2,
            can_delete=True,
        )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        FormSet = self._create_formset_class()
        if self.request.method == "POST":
            ctx["media_formset"] = FormSet(self.request.POST, self.request.FILES)
        else:
            ctx["media_formset"] = FormSet()
        return ctx

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        FormSet = self._create_formset_class()
        media_formset = FormSet(request.POST, request.FILES)

        if form.is_valid() and media_formset.is_valid():
            with transaction.atomic():
                self.object = form.save()
                media_formset.instance = self.object
                media_formset.save()

            messages.success(request, "Activité créée.")
            return redirect(self.get_success_url())

        context = self.get_context_data(form=form)

ouaf/ouaf_backoffice_app/templates/backoffice/animals/baseForm.html
<div class="form__row span-full"
     style="border:1px dashed var(--clr-primary-dark); padding:1rem; border-radius:var(--radius);">
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    <div class="form__row">
        <label class="form__label" for="{{ form.file.id_for_label }}">Fichier</label>
        {{ form.file }}
    </div>

    <div class="form__row">
        <label class="form__label" for="{{ form.url.id_for_label }}">URL</label>
        {{ form.url }}
        <p class="form__help">Image/vidéo distante ou URL YouTube. Laissez vide si vous uploadez un fichier.</p>
    </div>

    <div class="form__row">
        <label class="form__label" for="{{ form.caption.id_for_label }}">Légende</label>
        {{ form.caption }}
    </div>

    <div class="form__row">
        <label class="form__label" for="{{ form.position.id_for_label }}">Position</label>
        {{ form.position }}
    </div>

    {% if form.DELETE %}
    <div class="form__row">
        <label class="form__label" for="{{ mf.DELETE.id_for_label }}">Supprimer</label>
        {{ form.DELETE }}
    </div>
    {% endif %}

    <div class="fieldWrapper">
        {% for field in form.visible_fields %}
        {% if field.errors %}
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% endif %}
        {% endfor %}
    </div>
</div>

ouaf/ouaf_backoffice_app/templates/backoffice/animals/confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Suppression de l'animal {{animal.name}}</h1>
    <form method="post" action="{% url 'backoffice:animal_delete' animal.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
            {{form.errors}}
        {% endif %}
        {{ form }}
        <input type="submit" value="Confirmer">
        <input type="hidden" name="next" value="{{ next }}">
    </form>
{% endblock %}

ouaf/ouaf_backoffice_app/templates/backoffice/animals/form.html
{% extends "base.html" %}

{% block content %}
<h1>Ajout d'un nouvel animal</h1>
<form method="post" action="{% url 'backoffice:animal_create' %}" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.errors %}
    {{ form.errors }}
    {% endif %}

    {{ form }}

    {% if formset.errors %}
    {{ formset.errors }}
    {% endif %}

    {{ media_formset.management_form }}
    <div id="media-forms" class="formGrid">
        {% for mf in media_formset %}
            {{ mf }}
        {% endfor %}
    </div>

    <div>
        <input type="button" value="Ajouter un média" id="add-media" onclick="add_new_media()">
    </div>

    <div id="empty-form" style="display:none">
        {{ media_formset.empty_form }}
    </div>
    <script>
        function add_new_media()
        {
            let id_media_total_forms = document.getElementById('id_media-TOTAL_FORMS');
            let forms_list = document.getElementById('media-forms');
            let empty_form = document.getElementById('empty-form');
            let form_idx = id_media_total_forms.value;
            let new_div = document.createElement('div');
            new_div.innerHTML = empty_form.innerHTML.replace(/__prefix__/g, form_idx);
            forms_list.appendChild(new_div.firstElementChild);
            id_media_total_forms.value = parseInt(form_idx) + 1;
        }
    </script>

    <input type="submit" value="Confirmer">
    <input type="hidden" name="next" value="{{ next }}">
</form>


{% endblock %}

ouaf/ouaf_backoffice_app/templates/backoffice/animals/list.html
{% extends "base.html" %}

{% block content %}
<h1>Liste des animaux</h1>
<ul>
{% for animal in animal_list %}
    <li><span> <a href="{% url 'backoffice:animal_edit' animal.id %}">{{ animal.name }}</a></span></li>
{% endfor %}
</ul>
<a href="{% url 'backoffice:animal_create'%}">Ajouter un nouvel animal</a>

{% endblock %}

ouaf/ouaf_backoffice_app/templates/backoffice/animals/update.html
{% extends "base.html" %}

{% block content %}
<h1>Edition de l'animal {{animal.name}}</h1>
<form method="post" action="{% url 'backoffice:animal_edit' animal.id %}" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.errors %}
    {{form.errors}}
    {% endif %}

    {{ form }}

    {% if formset.errors %}
    {{formset.errors}}
    {% endif %}

    {{ media_formset.management_form }}
    <div id="media-forms" class="formGrid">
        {% for mf in media_formset %}
            {{ mf }}
        {% endfor %}
    </div>

    <div>
        <input type="button" value="Ajouter un média" id="add-media" onclick="add_new_media()">
    </div>

    <div id="empty-form" style="display:none">
        {{ media_formset.empty_form }}
    </div>
    <script>
        function add_new_media()
        {
            let id_media_total_forms = document.getElementById('id_media-TOTAL_FORMS');
            let forms_list = document.getElementById('media-forms');
            let empty_form = document.getElementById('empty-form');
            let form_idx = id_media_total_forms.value;
            let new_div = document.createElement('div');
            new_div.innerHTML = empty_form.innerHTML.replace(/__prefix__/g, form_idx);
            forms_list.appendChild(new_div.firstElementChild);
            id_media_total_forms.value = parseInt(form_idx) + 1;
        }
    </script>

    <input type="submit" value="Confirmer">
    <input type="hidden" name="next" value="{{ next }}">
</form>

<a href="{% url 'backoffice:animal_delete' animal.id%}">Supprimer l'animal</a>
<a href="{% url 'backoffice:animal_list' %}">Annuler</a>
{% endblock %}