ouaf/ouaf/urls.py
from django.contrib import admin
from django.urls import path, include, re_path, reverse_lazy
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views


urlpatterns = [
    #path("admin/", admin.site.urls), no need to use that because we include it in the urlspatterns
    path("", include('ouaf_app.urls')),
    path("index/", RedirectView.as_view(url="/", permanent=True)),
    path("i18n/", include("django.conf.urls.i18n")),
    # TO use i18n within JS scripts #
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path(
        "account/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html",
            success_url=reverse_lazy("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path("", include("ouaf_app.urls")),
    path("backoffice/", include('ouaf_backoffice_app.urls')),
    prefix_default_language=True,
)

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    # Dev
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + debug_toolbar_urls()
else:
    # Prod sans Nginx/Apache
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ouaf/ouaf_app/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.index, name='index'),
    path('account/logout', views.my_logout, name="my_logout"),
    path("account/", include("django.contrib.auth.urls")),
    path("registration/signup",views.signup_user, name="signup"),
    path("account/edit", views.account_edit, name="account_edit"),

    path("organisationChart", views.organisation_chart, name="organisation_chart"),

    path("mediationAnimale", views.mediation_animale, name="mediation_animale"),

    path("activities/", views.ActivityCategoryListView.as_view(), name="activities_list"),
    path("activities/category/<int:pk>/", views.ActivitiesByCategoryView.as_view(), name="activities_by_category"),

    path("animals/list", views.animal_list, name="animals_list"),
    path("animals/<int:animal_id>/detail/", views.animal_detail, name="animal_detail"),
    path("contact/", views.ContactView.as_view(), name="contact"),

    path("confidentialite", views.confidentialite, name="confidentialite")
    #account/login/ [name='login']
    #account/logout/ [name='logout']
    #account/password_change/ [name='password_change']
    #account/password_change/done/ [name='password_change_done']
    #account/password_reset/ [name='password_reset']
    #account/password_reset/done/ [name='password_reset_done']
    #account/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    #account/reset/done/ [name='password_reset_complete']
]

ouaf/ouaf_backoffice_app/urls.py
from django.urls import path, include
from . import views

app_name = "backoffice"

urlpatterns = [
    path("", views.BackofficeHome.as_view(), name="home"),

    path("users/", views.UserListView.as_view(), name="user_list"),
    path("users/<int:pk>/edit/", views.UserUpdateView.as_view(), name="user_edit"),

    path("activities/", views.ActivityListView.as_view(), name="activity_list"),
    path("activities/new/", views.ActivityCreateView.as_view(), name="activity_create"),
    path("activities/<int:pk>/", views.ActivityDetailView.as_view(), name="activity_detail"),
    path("activities/<int:pk>/update/", views.ActivityUpdateView.as_view(), name="activity_update"),
    path("activities/<int:pk>/delete/", views.ActivityDeleteView.as_view(), name="activity_delete"),
    path("activities/categories/new/modal/", views.ActivityCategoryCreateModalView.as_view(),
         name="activity_category_modal", ),

    path("events/", views.EventListView.as_view(), name="event_list"),
    path("events/new/", views.EventCreateView.as_view(), name="event_create"),
    path("events/<int:pk>/edit/", views.EventUpdateView.as_view(), name="event_edit"),
    path("events/<int:pk>/delete/", views.EventDeleteView.as_view(), name="event_delete"),

    path("animals/", views.AnimalListView.as_view(), name="animal_list"),
    path("animals/new", views.AnimalCreateView.as_view(), name="animal_create"),
    path("animals/<int:pk>/edit/", views.AnimalEditView.as_view(), name="animal_edit"),
    path("animals/<int:pk>/delete/", views.AnimalDeleteView.as_view(), name="animal_delete"),

    path("team/", views.TeamMemberListView.as_view(), name="team_list"),
    path("team/new", views.TeamMemberCreateView.as_view(), name="team_create"),
    path("team/<int:pk>/edit/", views.TeamMemberUpdateView.as_view(), name="team_update"),
    path("team/<int:pk>/delete/", views.TeamMemberDeleteView.as_view(), name="team_delete")
]

ouaf/ouaf_app/models.py
from mimetypes import guess_type

from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from django.conf import settings
from .groups import *
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

class Person(AbstractUser):
    """
    https://docs.djangoproject.com/en/dev/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser
    id
    password
    username (Special, Unique Constraint)
    first_name
    last_name
    email (Special)
    last_login
    is_staff : Returns True if the user is allowed to have access to the admin site.
    is_superuser : Designates that this user has all permissions without explicitly assigning them.
    is_active
    date_joined
    """
    email = models.EmailField(
        _("email address"),
        unique=True,
        error_messages={
            "unique": _("Un utilisateur avec cet email existe déjà."),
        },
    )
    address = models.CharField(_("Adresse"), max_length=1000)
    city = models.CharField(_("Ville"), max_length=100)
    country = models.CharField(_("Pays"), max_length=100)
    newsletter_subscription = models.BooleanField(_("Abonnement à la newsletter"), default=False)
    phone_number = PhoneNumberField(
        _("Téléphone"),
        region="FR",
        null=True,
        blank=False
    )

    def belongs_to_group(self, group_name):
        return self.groups.filter(name=group_name).exists()

    def set_group(self, group_name, value):
        group = Group.objects.get(name=group_name)
        self.groups.add(group) if value else self.groups.remove(group)

    class Meta:
        permissions = [
            ("can_change_user_role", _("Peut changer les rôles utilisateurs"))
        ]


class Event(models.Model):
    summary = models.CharField(_("Résumé"), max_length=500)
    description = models.TextField(_("Description"))
    start = models.DateTimeField(_("Date de début"))
    until = models.DateTimeField(_("Date de fin"))
    duration = models.DurationField(_("Durée"))
    organizer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Organisateur"),
        null=True,
        on_delete=models.SET_NULL,
        related_name="organiser2person"
    )
    attendees = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Participants"),
        related_name="attendees2person"
    )
    address = models.CharField(_("Adresse"), max_length=1000)
    latitude = models.FloatField(_("Latitude"))
    longitude = models.FloatField(_("Longitude"))
    is_published = models.BooleanField(_("Publié"), default=False)

    class Meta:
        permissions = [
            ("can_publish_event", _("Peut publier un événement")),
        ]


class MemberPayment(models.Model):
    personId = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Personne"),
        null=True,
        on_delete=models.SET_NULL
    )
    paymentDate = models.DateTimeField(_("Date de paiement"))
    amount = models.FloatField(_("Montant"))


class Animal(models.Model):
    name = models.CharField(_("Nom"), max_length=100)
    description = models.CharField(max_length=1000, null=True, blank=True)
    birth = models.DateField(_("Date de naissance"), null=True, blank=True)
    death = models.DateField(_("Date de décès"), null=True, blank=True)
    pet_amount = models.PositiveIntegerField(_("Nombre de caresses"), default=0, blank=True)


class OrganisationChartEntry(models.Model):
    first_name = models.CharField(_("Prénom"), max_length=1000)
    last_name = models.CharField(_("Nom"), max_length=1000)
    role = models.CharField(_("Rôle"), max_length=128)
    description = models.TextField(_("Description"), max_length=1000)
    photo = models.ImageField(_("Photo"), upload_to='images/organisationChart', blank=True)


class ActivityCategory(models.Model):
    title = models.CharField(_("Titre"), max_length=100)
    image = models.ImageField(_("Image"), upload_to='images/categories')

    def __str__(self):
        return self.title


class Activity(models.Model):
    title = models.CharField(_("Titre"), max_length=1000)
    category = models.ForeignKey(ActivityCategory, verbose_name=_("Catégorie"), null=True, blank=True,
                                 on_delete=models.CASCADE)
    description = models.TextField(_("Description"))


class AbstractMedia(models.Model):
    url = models.URLField(_("URL"), blank=True)
    caption = models.CharField(_("Légende"), max_length=200, blank=True)
    position = models.PositiveIntegerField(_("Position"), default=0)

    class Meta:
        abstract = True
        ordering = ["position", "id"]

    def __str__(self):
        return self.caption or (self.file.name if self.file else self.url or "media")

    @property
    def mime(self):
        src = self.file.name if self.file else self.url
        m, _ = guess_type(src or "")
        return m or ""

    @property
    def is_image(self):
        return self.mime.startswith("image/")

    @property
    def is_video(self):
        return self.mime.startswith("video") or ("youtu" in (self.url or ""))


class ActivityMedia(AbstractMedia):
    activity = models.ForeignKey(Activity, verbose_name=_("Activité"), on_delete=models.CASCADE, related_name="media")
    file = models.FileField(_("Fichier"), upload_to='activities/media', blank=True)

    class Meta:
        ordering = ["position", "id"]

class AnimalMedia(AbstractMedia):
    animal = models.ForeignKey(Animal, null=False, blank=False, on_delete=models.CASCADE, related_name='media')
    file = models.FileField(upload_to="animals/media", null=False, blank=False)
    def __str__(self):
        return f"{self.animal.name} - {super().__str__()}"
    class Meta:
        ordering = ["position", "id"]

ouaf/ouaf_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import PasswordInput
from .models import Person
from django import forms
import phonenumbers
from phonenumber_field.formfields import PhoneNumberField as PhoneFormField
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
import time


class RegistrationForm(UserCreationForm):
    username = forms.CharField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone_number = PhoneFormField(region="FR", required=True)

    class Meta:
        model = Person
        fields = [
            "first_name",
            "last_name",
            "email",
            "username",
            "address",
            "city",
            "country",
            "phone_number",
            "newsletter_subscription",
        ]
        widgets = {
            "password1": PasswordInput(),
            "password2": PasswordInput(),
        }


class PersonForm(forms.ModelForm):
    username = forms.CharField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone_number = PhoneFormField(region="FR", required=False)

    class Meta:
        model = Person
        fields = [
            "first_name",
            "last_name",
            "email",
            "username",
            "address",
            "city",
            "country",
            "phone_number",
            "newsletter_subscription",
        ]


class ContactForm(forms.Form):
    """
    Contact form with anti-spam protection.

    This form collects basic contact information (first name, last name,
    email, phone, and message) while implementing simple anti-spam
    mechanisms:
      - **Honeypot field**: A hidden field that should remain empty.
        If filled, the submission is flagged as spam.
      - **Timestamp field**: Ensures the form is not submitted too quickly
        (less than 3 seconds, typical of bots) and prevents submissions of
        expired forms (older than 1 hour).
      - **Phone number validation**: Uses the `phonenumbers` library to
        validate and normalize the phone number into E.164 format.

    Fields:
        honeypot (CharField): Hidden anti-spam field, must remain empty.
        ts (IntegerField): Timestamp set on form render, used to detect
            rapid or expired submissions.
        first_name (CharField): User's first name.
        last_name (CharField): User's last name.
        email (EmailField): User's email address.
        phone (CharField): User's phone number, validated and normalized.
        message (CharField): The content of the user's message.

    Validation:
        - `clean_honeypot()`: Raises a ValidationError if the field is filled.
        - `clean_ts()`: Ensures the form is not submitted too quickly
          and has not expired.
        - `clean_phone()`: Validates and formats the phone number
          using the `phonenumbers` library.
    """
    honeypot = forms.CharField(
        required=False,
        label="Laissez ce champ vide",
        widget=forms.TextInput(attrs={
            "autocomplete": "off",
            "tabindex": "-1",
            "aria-hidden": "true",
            "style": "position:absolute;left:-9999px;top:-9999px;height:0;width:0;padding:0;border:0;"
        })
    )
    ts = forms.IntegerField(widget=forms.HiddenInput)

    first_name = forms.CharField(
        label="Prénom",
        max_length=100,
        widget=forms.TextInput(attrs={"placeholder": "Votre prénom"})
    )
    last_name = forms.CharField(
        label="Nom",
        max_length=100,
        widget=forms.TextInput(attrs={"placeholder": "Votre nom"})
    )
    email = forms.EmailField(
        label="Adresse e-mail",
        widget=forms.EmailInput(attrs={"placeholder": "votre@email.com"})
    )
    phone = forms.CharField(
        label="Téléphone",
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "+33 6 12 34 56 78"})
    )
    message = forms.CharField(
        label="Votre message",
        widget=forms.Textarea(attrs={"placeholder": "Expliquez-nous votre demande…", "rows": 6})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.is_bound:
            self.fields["ts"].initial = int(time.time())

    def clean_honeypot(self):
        if self.cleaned_data.get("honeypot"):
            raise ValidationError("Spam détecté.")
        return ""

    def clean_ts(self):
        """Empêche la soumission ‘instantanée’ (bots) et les liens périmés."""
        now = int(time.time())
        ts = int(self.cleaned_data.get("ts") or 0)
        if now - ts < 3:
            raise ValidationError("Soumission trop rapide, veuillez réessayer.")
        if now - ts > 3600:
            raise ValidationError("Le formulaire a expiré, veuillez le recharger.")
        return ts

    def clean_phone(self):
        raw = self.cleaned_data.get("phone", "").strip()
        if not raw:
            return ""
        try:
            number = phonenumbers.parse(raw, "FR")
            if not phonenumbers.is_possible_number(number) or not phonenumbers.is_valid_number(number):
                raise forms.ValidationError("Le numéro de téléphone n'est pas valide.")
            return phonenumbers.format_number(number, phonenumbers.PhoneNumberFormat.E164)
        except phonenumbers.NumberParseException:
            raise forms.ValidationError("Le numéro de téléphone n'est pas valide.")

ouaf/ouaf_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600;700&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/main_css.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo_vectorise.svg' %}">

    <title>Les sourires d'Hindi{% block subtitle %}{% endblock %}</title>

    <!-- JQUERY + OWL CAROUSEL -->

    <!-- jQuery-->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

    <!-- OwlCarousel2 CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">

    <!-- OwlCarousel2 JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>


    <link rel="stylesheet" href="https://unpkg.com/cropperjs@1.6.2/dist/cropper.min.css">
    <script src="https://unpkg.com/cropperjs@1.6.2/dist/cropper.min.js"></script>
    <script defer src="{% static 'js/auto-cropper.js' %}"></script>


</head>
<body>
{% include "header.html" %}
<main>
    {% block content %}{% endblock %}
</main>
<footer>
    {% include "footer.html" %}
</footer>
</body>

<script type="text/javascript" src="{% static 'js/spin_effect.js' %}"></script>
</html>

ouaf/ouaf_app/templates/footer.html
{% load static %}

<div class="footer__inner">
    <div class="footer__top">
        <div class="footer__brand">
            <a href="/" class="footer__logo" aria-label="Aller à l'accueil">
                <img src="{% static 'images/logo_vectorise.svg' %}" alt="Logo Les Sourires d'Hindi">
            </a>
            <p class="footer__brandTagline">Redonner le sourire, une patte après l'autre</p>

            <ul class="footer__social" aria-label="Réseaux sociaux">
                <li><a class="footer__socialLink" target="_blank" href="https://www.instagram.com/lessouriresdhindi/"
                       aria-label="Instagram">Instagram</a></li>
                <li><a class="footer__socialLink" target="_blank"
                       href="https://www.facebook.com/profile.php?id=61576603605132" aria-label="Facebook">Facebook</a>
                </li>
                <li><a class="footer__socialLink" href="#" aria-label="LinkedIn">LinkedIn</a></li>
            </ul>
        </div>

        <nav class="footer__nav" aria-label="Liens utiles">
            <div class="footer__col">
                <h3 class="footer__colTitle">L’association</h3>
                <ul class="footer__list">
                    <li><a class="footer__link" href="#">Notre mission</a></li>
                    <li><a class="footer__link" href="{% url 'organisation_chart' %}">Équipe</a></li>
                </ul>
            </div>

            <div class="footer__col">
                <h3 class="footer__colTitle">Participer</h3>
                <ul class="footer__list">
                    <li><a href="{% url 'contact' %}?type=volunteer" class="footer__link">Devenir bénévole</a></li>
                    <li><a href="{% url 'contact' %}?type=adhesion" class="footer__link">
                        Adhérer</a></li>
                    <li><a class="footer__link" target="_blank"
                           href="https://www.paypal.com/paypalme/lessouriresdhindi">Faire un don</a></li>
                </ul>
            </div>

            <div class="footer__col">
                <h3 class="footer__colTitle">Événements</h3>
                <ul class="footer__list">
                    <li><a class="footer__link" href="#">À venir</a></li>
                    <li><a class="footer__link" href="#">Passés</a></li>
                </ul>
            </div>

            <div class="footer__col">
                <h3 class="footer__colTitle">Contact</h3>
                <ul class="footer__list">
                    <li><a class="footer__link" href="{% url 'contact' %}">Nous écrire</a></li>
                    <li><a class="footer__link" href="#">FAQ</a></li>
                </ul>
            </div>
        </nav>
    </div>

    <div class="footer__bottom">
        <p class="footer__copy">© {{ now|date:"Y" }} Les Sourires d’Hindi</p>
        <ul class="footer__legal">
            <li><a class="footer__legalLink" href="#">Mentions légales</a></li>
            <li><a class="footer__legalLink" href="#">CGU</a></li>
            <li><a class="footer__legalLink" href="{% url 'confidentialite' %}">Confidentialité</a></li>
            <li><a class="footer__legalLink" href="#">Cookies</a></li>
        </ul>
    </div>
</div>

ouaf/ouaf_app/templates/header.html
{% load static %}
<script defer src="{% static 'js/burger.js' %}"></script>
{# Skip link for accessibility #}
<a class="skiplink" href="#main">Aller au contenu</a>

<header class="header" role="banner">
    <div class="header__inner">
        <!-- Brand / Logo -->
        <div class="header__brand">
            <a href="{% url 'index' %}" class="header__logo" aria-label="Aller à l'accueil">
                <img src="{% static 'images/logo_vectorise.svg' %}" alt="Logo Les Sourires d'Hindi"
                     class="header__logoImg">
                <span class="header__brandName">Les Sourires d’Hindi</span>
            </a>
        </div>

        <!-- Mobile toggle -->
        <button class="header__toggle" aria-expanded="false" aria-controls="site-nav">
            <span class="header__toggleIcon" aria-hidden="true"></span>
            <span class="sr-only"></span>
        </button>

        <!-- Primary navigation -->
        <nav id="site-nav" class="header__nav" aria-label="Navigation principale">
            <ul class="header__list">
                <li class="header__item">
                    <a class="header__link {% if request.resolver_match.url_name == 'index' %}is-active{% endif %}"
                       href="{% url 'index' %}">Accueil</a>
                </li>
                <li class="header__item">
                    <a class="header__link {% if request.resolver_match.url_name == 'organisation_chart' %}is-active{% endif %}"
                       href="{% url 'organisation_chart' %}">Trombinoscope</a>
                </li>
                <li class="header__item">
                    <a class="header__link {% if request.resolver_match.url_name == 'mediation_animale' %}is-active{% endif %}"
                       href="{% url 'mediation_animale' %}">Médiation animale</a>
                </li>
                <li class="header__item">
                    <a class="header__link {% if request.resolver_match.url_name == 'activities_list' %}is-active{% endif %}"
                       href="{% url 'activities_list' %}">Activités</a>
                </li>
                <li class="header__item">
                    <a class="header__link {% if request.resolver_match.url_name == 'animals_list' %}is-active{% endif %}"
                       href="{% url 'animals_list' %}">Animaux</a>
                </li>
                <li class="header__item">
                    <a class="header__link {% if request.resolver_match.url_name == 'contact' %}is-active{% endif %}"
                       href="{% url 'contact' %}">Contact</a>
                </li>
            </ul>

            <div class="header__user">
                <a class="header__dropdown__text">Mon compte</a>
                <ul class="header__user__content">
                    {% if user.is_authenticated %}
                        <li class="header__item">
                            <span class="header__greet">Hi {{ user.username }} !</span>
                        </li>
                        {% if perms.ouaf_app.view_event %}
                            <li class="header__item">
                                <a class="header__link" href="{% url 'backoffice:home' %}">Backoffice</a>
                            </li>
                        {% endif %}
                        <li class="header__item">
                            <a class="header__link" href="{% url 'account_edit' %}">Mes informations</a>
                        </li>
                        <li class="header__item">
                            <a class="header__link" href="{% url 'my_logout' %}">Déconnexion</a>
                        </li>
                    {% else %}
                        <li class="header__item">
                            <a class="header__link" href="{% url 'signup' %}">S'inscrire</a>
                        </li>
                        <li class="header__item">
                            <a class="header__link" href="{% url 'login' %}">Connexion</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
</header>

ouaf/ouaf_app/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<section class="index__section">
    <img
            class="index__section__main_logo"
            src="{% static 'images/logo_vectorise.svg' %}"
            loading="lazy"
            decoding="async"
    />

    {% include "html/ouaf_h1.html" with text="Notre association" %}

    <p class="index__section__main_text">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit
        amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper
        congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl
        sit amet erat. Duis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue.
        Ut in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. Praesent
        blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. Vestibulum ante ipsum primis in faucibus orci
        luctus et ultrices posuere cubilia Curae; Aliquam nibh. Mauris ac mauris sed pede pellentesque fermentum. Maecenas
        adipiscing ante non diam sodales hendrerit.

        Ut velit mauris, egestas sed, gravida nec, ornare ut, mi. Aenean ut orci vel massa suscipit pulvinar. Nulla
        sollicitudin. Fusce varius, ligula non tempus aliquam, nunc turpis ullamcorper nibh, in tempus sapien eros vitae
        ligula. Pellentesque rhoncus nunc et augue. Integer id felis. Curabitur aliquet pellentesque diam. Integer quis
        metus vitae elit lobortis egestas. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi vel erat non
        mauris convallis vehicula. Nulla et sapien. Integer tortor tellus, aliquam faucibus, convallis id, congue eu, quam.
        Mauris ullamcorper felis vitae erat. Proin feugiat, augue non elementum posuere, metus purus iaculis lectus, et
        tristique ligula justo vitae magna.
        Aliquam convallis sollicitudin purus. Praesent aliquam, enim at fermentum mollis, ligula massa adipiscing nisl, ac
        euismod nibh nisl eu lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod libero eu enim. Nulla nec
        felis sed leo placerat imperdiet. Aenean suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla tincidunt
        tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus, felis magna fermentum augue, et ultricies lacus lorem
        varius purus. Curabitur eu amet.
    </p>
</section>

{% endblock %}

ouaf/ouaf_app/templates/organisationChart.html
{% extends "base.html" %}
{% load static %}

{% block subtitle %} – Trombinoscope{% endblock %}

{% block content %}
<section class="team" aria-labelledby="team-title">
  <header class="team__header">
    <h1 id="team-title">L'équipe</h1>
  </header>

  <ul class="team__list" role="list">
    {% for member in organisation_members %}
      <li class="team__card">
        <article class="team__person" aria-labelledby="team-name-{{ forloop.counter }}">
          <figure class="team__figure">
            <div class="team__photoWrap">
              {% if member.photo %}
                <img
                  class="team__photo"
                  src="{{ member.photo.url }}"
                  alt="Portrait de {{ member.first_name }} {{ member.last_name }}"
                  loading="lazy"
                  decoding="async"
                />
              {% else %}
                <img
                  class="team__photo"
                  src="{% static 'images/avatar_placeholder.svg' %}"
                  alt="Portrait de {{ member.first_name }} {{ member.last_name }}"
                  loading="lazy"
                  decoding="async"
                />
              {% endif %}
            <div class="spin_target">
              <img
                class="team__badgeDog spin-target"
                src="{% static 'images/chien.svg' %}"
                alt=""
                aria-hidden="true"
                loading="lazy"
                decoding="async"
              />
            </div>
            </div>

            <figcaption class="team__caption">
              <h3 class="team__name" id="team-name-{{ forloop.counter }}">
                <strong>{{ member.first_name }} {{ member.last_name }}</strong>
              </h3>
              <h3 class="team__name" id="team-name-{{ forloop.counter }}">
                <strong> - </strong>
              </h3>
              <h3 class="team__name" id="team-name-{{ forloop.counter }}">
                <strong>{{ member.role }}</strong>
              </h3>

              {% if member.description %}
                <p class="team__bio">
                  {{ member.description }}
                </p>
              {% endif %}
            </figcaption>
          </figure>
        </article>
      </li>
    {% empty %}
      <li class="team__empty">Aucun membre pour le moment.</li>
    {% endfor %}
  </ul>
</section>
{% endblock %}